app_market/urls.py
from django.urls import path
from .views import index,my_search,product_detail,blog,blog_detail,product_comment,product_list_by_category,faq

app_name = 'app_market'

urlpatterns = [
    path('',index,name='home'),
    path('search/', my_search, name='search'),
    path('product/<int:id>/', product_detail, name='product_detail'),
    path('product/<int:id>/comment/', product_comment, name='p_comment'),
    path('blog/', blog , name='blog' ),
    path('blog/detail/', blog_detail , name='blogdetail' ),
    path('products/category/<int:category_id>/', product_list_by_category, name='product_list_by_category'),
    path('faq/', faq, name='faq'),

]

merch_market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_market.urls')),
    path('', include('app_account.urls')),
    path('', include('app_payment.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_market/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse

User = get_user_model()

class Product(models.Model):
    name_fa = models.CharField(max_length=255, null=True)
    name_en = models.CharField(max_length=255, null=True)
    price = models.PositiveIntegerField()
    discount = models.IntegerField(default=0)
    count = models.PositiveIntegerField()
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    is_suggested = models.BooleanField(default=False)
    is_amazing = models.BooleanField(default=False)
    footer_right = models.BooleanField(default=False)
    footer_left = models.BooleanField(default=False)
    footer_Middle = models.BooleanField(default=False)
    Category = models.ManyToManyField('Category')
    color = models.ManyToManyField('color')
    features = models.ManyToManyField('features')

    @property
    def images(self):
        return Image.objects.filter(
            object_id=self.id,
            content_type=ContentType.objects.get_for_model(self.__class__).id
        )

    def get_absolute_url(self):
        return reverse('app_market:product_detail', args=(self.id, ))

    def discounted_price(self):
        if self.discount > 0:
            return self.price - (self.price * self.discount // 100)
        return self.price
    
    def __str__(self):
        return self.name_fa or ''

class Color(models.Model):
    color = models.CharField(max_length=255)
    hex_code = models.CharField(max_length=35,null=True)

    def __str__(self):
        return self.color

class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Banner(models.Model):
    title = models.CharField(max_length=255)

    @property
    def images(self):
        return Image.objects.filter(
            object_id=self.id,
            content_type=ContentType.objects.get_for_model(self.__class__).id
        )

    def __str__(self):
        return self.title

class Category(models.Model):
    parent = models.ForeignKey( 'self', related_name='sub_categories', on_delete=models.SET_NULL, null=True, blank=True )
    name = models.CharField(max_length=50 , null=True)
    slug = models.SlugField(max_length=50 , null=True , blank=True)
    is_available = models.BooleanField(default= True)

    def __str__(self):
        return self.name
    
class features(models.Model):
    text = models.CharField(max_length=255)
    answer = models.CharField(max_length=255,null=True)

    def __str__(self):
        return self.text
    
class review(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='review' , null=True)
    description = models.TextField(blank=True , null=True)

class special_feature(models.Model):
    text = models.CharField(max_length=255,null=True)
    main_text = models.TextField(null=True)
    review = models.ForeignKey("review", on_delete=models.CASCADE , related_name='feature' , null=True)

    def __str__(self):
        return self.text

class ProductDescription(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='descriptions')
    title = models.CharField(max_length=100 , blank=True , null=True)
    description = models.TextField( blank=True , null=True )

    def __str__(self):
        return self.title
    
class Blog(models.Model):
    title = models.CharField(max_length=255)

    @property
    def images(self):
        return Image.objects.filter(
            object_id=self.id,
            content_type=ContentType.objects.get_for_model(self.__class__).id
        )

    def __str__(self):
        return self.title
    
class Blog_detail(models.Model):
    title = models.CharField( max_length=150 , blank=True , null=True)
    description= models.TextField()

    @property
    def images(self):
        return Image.objects.filter(
            object_id=self.id,
            content_type=ContentType.objects.get_for_model(self.__class__).id
        )

    def __str__(self):
        return self.title
    
class Image(models.Model):
    url = models.CharField(max_length=150, null=True, blank=True)
    image = models.ImageField(upload_to='store/images/', null=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, related_name='app_market_images')
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return self.image.url
    

app_market/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField( label='search' , max_length=100 )

app_market/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Banner,Product,Category,Blog,Blog_detail
from django.db.models import Q
from app_social.models import Comment,Question
from app_social.forms import CommentForm,QuestionForm,AnswerForm
from django.contrib.auth.decorators import login_required

def index(request):
    context = {
        'banner_images': Banner.objects.get(title='index_banner').images,
        'products': Product.objects.all(),
        'sugessted_products': Product.objects.filter(is_suggested=True),
        'amazing_products': Product.objects.filter(is_amazing=True),
        'footer_right': Product.objects.filter(footer_right=True),
        'footer_left': Product.objects.filter(footer_left=True),
        'footer_Middle': Product.objects.filter(footer_Middle=True),
        'category': Category.objects.all()
    }
    return render(request , 'index.html', context)


def my_search(request):
    query = request.GET.get('q')
    if query is not None:
        serch_products = Product.objects.filter( Q(name_fa__icontains=query) | Q(name_en__icontains=query) )
    else:
        serch_products = Product.objects.all()
    return render(request, 'search.html', {'serch_products': serch_products})

@login_required
def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    question_count = Question.objects.filter(product=product).count()
    comments_count = Comment.objects.filter(product=product).count()
    comments = Comment.objects.filter(product=product)
    questions = Question.objects.filter(product=product)

    question_form = QuestionForm()

    if request.method == 'POST':
        if 'vote_type' in request.POST:
            comment_id = request.POST.get('comment_id')
            vote_type = request.POST.get('vote_type')
            comment = get_object_or_404(Comment, id=comment_id)

            if vote_type == 'helpful':
                comment.helpful_count += 1
            elif vote_type == 'not_helpful':
                comment.not_helpful_count += 1

            comment.save()
            return redirect('app_market:product_detail', id=product.id)

        elif 'question_text' in request.POST:
            question_form = QuestionForm(request.POST)
            if question_form.is_valid():
                question = question_form.save(commit=False)
                question.product = product
                question.user = request.user  
                question.save()
                return redirect('app_market:product_detail', id=product.id)

        elif 'answer_text' in request.POST:
            answer_form = AnswerForm(request.POST)
            if answer_form.is_valid():
                question_id = request.POST.get('question_id')  
                question = get_object_or_404(Question, id=question_id)
                
               
                if not hasattr(question, 'answer'):
                    answer = answer_form.save(commit=False)
                    answer.question = question
                    answer.user = request.user 
                    answer.save()
                return redirect('app_market:product_detail', id=product.id)

    context = {
        'product': product,
        'comments': comments,
        'questions': questions,
        'question_form': question_form,
        'question_count': question_count, 
        'comment_count': comments_count,
        'category': Category.objects.all()
    }

    if product.count > 0:
        return render(request, 'product-detail.html', context)
    else:
        return render(request, 'single-product-not-available.html', context)
        
def product_comment(request, id):
    product = Product.objects.get(id=id)
    comments = Comment.objects.all()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = product
            comment.user = request.user
            comment.save()
            return redirect('app_market:product_detail', id=product.id)
    else:
        form = CommentForm()

    return render(request, 'product-comment.html', {
        'product': product,
        'comments': comments,
        'form': form,
        'category': Category.objects.all()
    })
        
def blog(request):
    context = {
        'blog':Blog.objects.all(),
        'category': Category.objects.all()  
         
    }
   
    return render(request, 'blog.html', context)

def blog_detail(request):
     context = {
          'blog_detail':Blog_detail.objects.all(),
          'category': Category.objects.all()
     }
     return render(request,'blog_detail.html',context)


def product_list_by_category(request, category_id):
    main_category= Category.objects.all()
    category = get_object_or_404(Category, id=category_id)
    products = Product.objects.filter(Category=category)
    return render(request, 'product_list.html', {'products_list': products, 'category_list': category , 'category':main_category})


def faq(request):
    return render(request,'page-faq-category.html')



        

app_market/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="fa">

<!-- Start main-content -->
    <main class="main-content dt-sl mb-3">
        <div class="container main-container">
            <div class="row mt-5 pt-5">
                <div class="col-lg-8 col-md-12 col-sm-12 col-12 mb-3">
                    <div class="row">
                        {% for item in blog %}
                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="post-card">
                                <div style="left:0" class="post-thumbnail">
                                    <a href="{% url 'app_market:blogdetail' %}">
                                        <img src="{{ item.images.first.image.url }}" alt="">
                                    </a>
                                    <span class="post-tag">مقاله</span>

                                </div>
                                <h7>
                                <div style="text-align:center" class="post-title">
                                    <a href="{% url 'app_market:blogdetail' %}">
                                        {{item.title}}
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </main>
<!-- End main-content -->
        
{% endblock content %}

app_market/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="fa">
        <!-- Start main-content -->
        <main class="main-content dt-sl mb-3">
            <div class="container main-container">
                <!-- Start title - breadcrumb -->
                {% for item in blog_detail %}
                    <div class="title-breadcrumb-special dt-sl">
                        <div class="title-page dt-sl">
                            <h1>  {{item.title}} </h1>
                        </div>
                    </div>
                    <!-- End title - breadcrumb -->
                    <div class="row">
                        <div class="col-lg-12 col-md-8 col-sm-12 col-12 mb-3">
                            <div class="content-page">
                                <div class="content-desc dt-sn dt-sl">
                                    <div class="post-thumbnail dt-sl">
                                        <img src="{{ item.images.first.image.url }}" alt="">
                                    </div>
                                    <p align="justify"><span style="color: #ff0000;"> {{item.title}} </span> {{item.description}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        <!-- End main-content -->
{% endblock content %}

app_market/templates/page-faq-category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Start main-content -->
        <main class="main-content dt-sl mb-3">
            <div class="page-cover mb-2">
                <div class="page-cover-title">
                    <h1>پاسخ پرسش‌های پرتکرار</h1>
                    <div class="form-ui">
                        <form action="">
                         
                        </form>
                    </div>
                </div>
            </div>
            <div class="container main-container">
                <div class="row">
                    <div class="col-12">
                        <div class="page info-page-cats dt-sl dt-sn pt-3 pb-2">
                            <div class="row">
                                <div class="col-12 pr-4 mb-3">
                                    <div class="section-title title-wide no-title-wide-before mb-1 no-after-title-wide">
                                        <img src="./assets/img/faq/1.png" width="60" alt="">
                                        <h2 class="font-weight-bold">ورود و ثبت نام</h2>
                                    </div>
                                </div>
                                <div class="col-12 filter-product mb-3">
                                    <div class="accordion" id="accordionExample">
                                      
                                        <div class="card">
                                            <div class="card-header" id="headingTwo">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseTwo"
                                                        aria-expanded="false" aria-controls="collapseTwo">
                                                        میتوانم سفارش خود را در محل پرداخت کنم؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>بله شما میتوانید سفارش خود را هنگام تحویل کالا پرداخت کنید، در
                                                        برخی موارد امکان پرداخت سفارش در محل وجود ندارد.</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-header" id="headingThree">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseThree"
                                                        aria-expanded="false" aria-controls="collapseThree">
                                                        چطور درخواست خود را جهت مرجوعی کالا به شما اطلاع دهم؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>شما میتوانید از طریق فرم درخواست مرجوعی در پروفایل ، صفحه تماس با
                                                        ما و تلفن درخواست خود را ثبت نمایید.</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-header" id="headingFour">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseFour"
                                                        aria-expanded="false" aria-controls="collapseFour">
                                                        چطور میتوانم سفارشم را لغو کنم ؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>شما میتوانید با مراجعه به پروفایل خود سفارش یا مرسوله ایی که از
                                                        ارسال آن منصرف شدید را لغو نمایید.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="page dt-sl dt-sn pb-2 mb-4">
                            <div class="row">
                                <div class="col-12 pr-4 mb-3">
                                    <div class="section-title title-wide mb-1 no-after-title-wide">
                                        <h2 class="font-weight-bold">پرتکرارترین پرسش‌ها</h2>
                                    </div>
                                </div>
                                <div class="col-12 filter-product mb-3">
                                    <div class="accordion" id="accordionExample">
                                      
                                        <div class="card">
                                            <div class="card-header" id="headingTwo">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseTwo"
                                                        aria-expanded="false" aria-controls="collapseTwo">
                                                        میتوانم سفارش خود را در محل پرداخت کنم؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>بله شما میتوانید سفارش خود را هنگام تحویل کالا پرداخت کنید، در
                                                        برخی موارد امکان پرداخت سفارش در محل وجود ندارد.</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-header" id="headingThree">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseThree"
                                                        aria-expanded="false" aria-controls="collapseThree">
                                                        چطور درخواست خود را جهت مرجوعی کالا به شما اطلاع دهم؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>شما میتوانید از طریق فرم درخواست مرجوعی در پروفایل ، صفحه تماس با
                                                        ما و تلفن درخواست خود را ثبت نمایید.</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-header" id="headingFour">
                                                <h2 class="mb-0">
                                                    <button class="btn btn-block text-right collapsed" type="button"
                                                        data-toggle="collapse" data-target="#collapseFour"
                                                        aria-expanded="false" aria-controls="collapseFour">
                                                        چطور میتوانم سفارشم را لغو کنم ؟
                                                        <i class="mdi mdi-chevron-down"></i>
                                                    </button>
                                                </h2>
                                            </div>
                                            <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                                                data-parent="#accordionExample">
                                                <div class="card-body">
                                                    <p>شما میتوانید با مراجعه به پروفایل خود سفارش یا مرسوله ایی که از
                                                        ارسال آن منصرف شدید را لغو نمایید.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </main>
        <!-- End main-content -->
{% endblock content %}

app_market/templates/product_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Start main-content -->
    <main class="main-content dt-sl mb-3">
        <div class="container main-container">
            <div class="row">
                <!-- Start Content -->
                <div class="col-lg-12 col-md-12 col-sm-12 search-card-res">
                    <div class="d-md-none">
                        <button class="btn-filter-sidebar">
                            جستجوی پیشرفته <i class="fad fa-sliders-h"></i>
                        </button>
                    </div>
                    <div class="dt-sl dt-sn px-0 search-amazing-tab">
                        <div class="ah-tab-wrapper dt-sl">
                            <div class="ah-tab dt-sl">
                                <a class="ah-tab-item" data-ah-tab-active="true" href="">مرتبط ترین</a>
                            </div>
                        </div>
                        <div class="ah-tab-content-wrapper dt-sl px-res-0">
                            <div class="ah-tab-content dt-sl" data-ah-tab-active="true">
                                <div class="row mb-3 mx-0 px-res-0" id="productResults"  >
                                    {% for product in products_list %}
                                    <div class="col-lg-3 col-md-4 col-sm-6 col-12 px-10 mb-1 px-res-0">
                                        <div class="product-card mb-2 mx-res-0">
                                            <div class="product-head">
                                                <div class="rating-stars">
                                                </div>
                                            </div>
                                            <a class="product-thumb" href="{{ product.get_absolute_url }}">
                                                <img src="{{ product.images.first.image.url }}" alt="Product Thumbnail">
                                            </a>
                                            <div class="product-card-body">
                                                <h5 class="product-title">
                                                    <a href="{{ product.get_absolute_url }}"> {{ product.name_fa }} </a>
                                                </h5>
                                                <a class="product-meta" href="{{ product.get_absolute_url }}">
                                                    {% for category in product.Category.all %}
                                                        {{ category.name }}{% if not forloop.last %}،{% endif %}
                                                    {% endfor %}
                                                </a>
                                                <span class="product-price">{{ product.price|intcomma }} تومان</span>
                                            </div>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <p>هیچ محصولی یافت نشد.</p>
                                    {% endfor %}
                                </div>
                                {% comment %} <div class="row">
                                    <div class="col-12">
                                        <div class="pagination">
                                            <a href="#" class="prev"><i
                                                    class="mdi mdi-chevron-double-right"></i></a>
                                            <a href="#">1</a>
                                            <a href="#" class="active-page">2</a>
                                            <a href="#">3</a>
                                            <a href="#">4</a>
                                            <a href="#">...</a>
                                            <a href="#">7</a>
                                            <a href="#" class="next"><i class="mdi mdi-chevron-double-left"></i></a>
                                        </div>
                                    </div>
                                </div> {% endcomment %}
                            </div> 
                        </div>
                    </div>
                </div>
                <!-- End Content -->
            </div>
        </div>
    </main>
    <!-- End main-content -->
{% endblock content %}        