app_account/urls.py
from django.urls import path
from .views import loginview,logoutview,signupview,welcomeview,profileview,profile_editview,profile_address,pass_changeview

urlpatterns = [
    path("login/", loginview, name="login" ),
    path('logout/', logoutview , name = 'logout'),
    path("register/", signupview, name="register"),
    path("welcome/", welcomeview, name="welcome"),
    path("profile/", profileview, name="profile"),
    path("profile/edit/", profile_editview , name="profile_edit"),
    path("profile/address/", profile_address , name="profile_address"),
    path("profile/password-change/", pass_changeview , name="pass_change"),
]

app_market/urls.py
from django.urls import path
from .views import index,my_search,product_detail,blog,blog_detail,product_comment,product_list_by_category,faq

app_name = 'app_market'

urlpatterns = [
    path('',index,name='home'),
    path('search/', my_search, name='search'),
    path('product/<int:id>/', product_detail, name='product_detail'),
    path('product/<int:id>/comment/', product_comment, name='p_comment'),
    path('blog/', blog , name='blog' ),
    path('blog/detail/', blog_detail , name='blogdetail' ),
    path('products/category/<int:category_id>/', product_list_by_category, name='product_list_by_category'),
    path('faq/', faq, name='faq'),

]

merch_market/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_market.urls')),
    path('', include('app_account.urls')),
    path('', include('app_payment.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_account/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    phone_number = models.CharField(max_length=255)
    national_id = models.CharField(max_length=255,blank=True)
    image = models.ImageField(upload_to='store/images/', null=True)

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    postal_code = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

app_account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from .models import Profile,Address
from django.core.exceptions import ValidationError

user = get_user_model()

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = user
        fields = ('username', 'email', 'password1', 'password2')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number', 'national_id', 'image']

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['postal_code', 'description']

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput, label="رمز عبور فعلی")
    new_password = forms.CharField(widget=forms.PasswordInput, label="رمز عبور جدید")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput, label="تکرار رمز عبور جدید")

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_current_password(self):
        current_password = self.cleaned_data.get('current_password')
        if not self.user.check_password(current_password):
            raise ValidationError("رمز عبور فعلی اشتباه است.")
        return current_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_new_password = cleaned_data.get('confirm_new_password')

        if new_password != confirm_new_password:
            raise ValidationError("رمز عبور جدید و تکرار آن یکسان نیستند.")

        return cleaned_data

app_account/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login,logout, update_session_auth_hash
from .forms import SignupForm
from django.contrib import messages
from app_market.models import Category
from .forms import UserForm, ProfileForm, AddressForm , ChangePasswordForm
from django.contrib.auth.decorators import login_required
from .models import Profile,Address

def welcomeview(request):
    return render(request,'welcome.html')

def loginview(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/')
    return render(request,'login.html')

def logoutview(request):
    logout(request)
    return redirect('login')

def signupview(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('welcome')
    else:
        form = SignupForm()
    return render(request , 'register.html' , {'form':form})

def profileview(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    context = {
        'category': Category.objects.all(),
        'profile': profile,
    }
    return render(request,'profile.html',context)

@login_required
def profile_editview(request):
    profile, created = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(request, 'profile-additional-info.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'profile': profile,
        'category': Category.objects.all() 
    })

@login_required
def profile_address(request):

    if request.method == 'POST':
        if 'delete_address_id' in request.POST: 
            address_id = request.POST.get('delete_address_id')
            address = get_object_or_404(Address, id=address_id, user=request.user)
            address.delete()  
            return redirect('profile_address')
            
        
        else: 
            form = AddressForm(request.POST)
            if form.is_valid():
                address = form.save(commit=False)
                address.user = request.user
                address.save()
                return redirect('profile_address') 
    else:
        form = AddressForm()

    addresses = Address.objects.filter(user=request.user)
    profile, created = Profile.objects.get_or_create(user=request.user)

    return render(request, 'profile-addresses.html', {
        'form': form,
        'addresses': addresses ,
        'profile': profile,
        'category': Category.objects.all() 
    })

@login_required
def pass_changeview(request):
    if request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            request.user.set_password(new_password)
            request.user.save()
            update_session_auth_hash(request, request.user)

            messages.success(request, 'رمز عبور با موفقیت تغییر یافت.')
            return redirect('profile')
    else:
        form = ChangePasswordForm(user=request.user)

    return render(request, 'password-change.html', {'form': form})

app_account/templates/login.html
{% load static %}
<!DOCTYPE html>

<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#009688">
    <meta name="msapplication-navbutton-color" content="#009688">
    <meta name="apple-mobile-web-app-status-bar-style" content="#009688">
    <title>didikala | Login Page</title>
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static '/assets/css/vendor/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/materialdesignicons.min.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static '/assets/css/vendor/bootstrap.min.css' %}">
    <!-- Plugins -->
    <link rel="stylesheet" href="{% static '/assets/css/vendor/bootstrap-slider.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/jquery.horizontalmenu.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/jquery-stack-menu.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/nice-select.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/vendor/nouislider.min.css' %}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static '/assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/colors/orange-color.css' %}" id="colorswitch">
</head>

<body>
    <div class="wrapper">
        <!-- Start main-content -->
        <main class="main-content dt-sl mt-4 mb-3">
            <div class="container main-container">
                <div class="row">
                    <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                        {{ user.username }}
                        <div class="logo-area text-center mb-3">
                            <a href="#"><img src="{% static '/assets/img/logo.png' %}" class="img-fluid" alt="logo"></a>
                        </div>
                        <div class="auth-wrapper form-ui border pt-4">
                            <div class="section-title title-wide mb-1 no-after-title-wide">
                                <h2 class="font-weight-bold">ورود</h2>
                            </div>
                            <form action="{% url "login" %}" method="post" >
                                {% csrf_token %}
                                <div class="form-row-title">
                                    {% comment %} <h3>ایمیل یا شماره موبایل</h3> {% endcomment %}
                                    <h3>نام کاربری</h3>
                                </div>
                                <div class="form-row with-icon">
                                    <input type="text" name="username" class="input-ui pr-2"
                                        {% comment %} placeholder="ایمیل یا شماره موبایل خود را وارد نمایید"> {% endcomment %}
                                        placeholder="نام کاربری خود را وارد کنید">
                                    <i class="mdi mdi-account-circle-outline"></i>
                                </div>
                                <div class="form-row-title">
                                    <h3>رمز عبور</h3>
                                </div>
                                <div class="form-row with-icon">
                                    <input type="password" name="password" class="input-ui pr-2"
                                        placeholder="رمز عبور خود را وارد نمایید">
                                    <i class="mdi mdi-lock-open-variant-outline"></i>
                                </div>
                                <div class="form-row mt-2">
                                    <div class="custom-control custom-checkbox float-right mt-2">
                                        <input type="checkbox" class="custom-control-input" id="customCheck3">
                                        <label class="custom-control-label" for="customCheck3">
                                            مرا به خاطر بسپار
                                        </label>
                                    </div>
                                </div>
                                <div class="form-row mt-3">
                                    <button class="btn-primary-cm btn-with-icon mx-auto w-100">
                                        <i class="mdi mdi-login-variant"></i>
                                        ورود به مرچ مارکت
                                    </button>
                                </div>
                            </form>
                            <div class="form-footer mt-3">
                                <div>
                                    <span class="font-weight-bold">کاربر جدید هستید؟</span>
                                    <a href="{% url 'register' %}" class="mr-3 mt-2">ثبت نام در مرچ مارکت</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- End main-content -->
        <!-- Start mini-footer -->
        <footer class="mini-footer dt-sl">
            <div class="container main-container">
                <div class="row">
                    <div class="col-12">
                        <ul class="mini-footer-menu">
                            <li><a href="{% url 'app_market:blog' %}">درباره مرچ مارکت</a></li>
                        </ul>
                    </div>
                    <div class="col-12 mt-2 mb-3">
                        <div class="footer-light-text">
                            استفاده از مطالب فروشگاه اینترنتی مرچ مارکت فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                            است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین مرچ مارکت) می‌باشد.
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <div class="copy-right-mini-footer">
                            MERCH MARKET
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End mini-footer -->
    </div>
    <!-- colorPanel -->
    <div id="colorswitch-option">
        <button><i class="mdi mdi-settings"></i></button>
        <ul>
            <li class="active" data-path="{% static '/assets/css/colors/default.css' %}"><span
                    style="background-color: #f7858d;"></span></li>
            <li data-path="{% static '/assets/css/colors/amber-color.css' %}"><span style="background-color: #ffab00;"></span></li>
            <li data-path="{% static '/assets/css/colors/blue-color.css' %}"><span style="background-color: #2979ff;"></span></li>
            <li data-path="{% static '/assets/css/colors/blue-grey-color.css' %}"><span style="background-color: #607d8b;"></span>
            </li>
            <li data-path="{% static '/assets/css/colors/brown-color.css' %}"><span style="background-color: #795548;"></span></li>
            <li data-path="{% static '/assets/css/colors/cyan-color.css' %}"><span style="background-color: #00bcd4;"></span></li>
            <li data-path="{% static '/assets/css/colors/green-color.css' %}"><span style="background-color: #4caf50;"></span></li>
            <li data-path="{% static '/assets/css/colors/indigo-color.css' %}"><span style="background-color: #3f51b5;"></span></li>
            <li data-path="{% static '/assets/css/colors/lime-color.css' %}"><span style="background-color: #cddc39;"></span></li>
            <li data-path="{% static '/assets/css/colors/orange-color.css' %}"><span style="background-color: #ff9800;"></span></li>
            <li data-path="{% static '/assets/css/colors/red-color.css' %}"><span style="background-color: #f44336;"></span></li>
            <li data-path="{% static '/assets/css/colors/teal-color.css' %}"><span style="background-color: #009688;"></span></li>
            <li data-path="{% static '/assets/css/colors/purple-color.css' %}"><span style="background-color: #9c27b0;"></span></li>
        </ul>
    </div>
    <!-- end colorPanel -->
    <!-- Core JS Files -->
    <script src="{% static '/assets/js/vendor/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/bootstrap.min.js' %}"></script>
    <!-- Plugins -->
    <script src="{% static '/assets/js/vendor/bootstrap-slider.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/owl.carousel.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/owl.carousel2.thumbs.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/jquery.nice-select.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/nouislider.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/jquery.horizontalmenu.js' %}"></script>
    <script src="{% static '/assets/js/vendor/jquery-stack-menu.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/jquery.fancybox.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/countdown.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/wNumb.js' %}"></script>
    <script src="{% static '/assets/js/vendor/ResizeSensor.min.js' %}"></script>
    <script src="{% static '/assets/js/vendor/theia-sticky-sidebar.min.js' %}"></script>
    <!-- Main JS File -->
    <script src="{% static '/assets/js/main.js' %}"></script>
</body>

</html>

app_account/templates/password-change.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#009688">
    <meta name="msapplication-navbutton-color" content="#009688">
    <meta name="apple-mobile-web-app-status-bar-style" content="#009688">
    <title>didikala | Password-change Page</title>
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static "/assets/css/vendor/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/materialdesignicons.min.css" %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "/assets/css/vendor/bootstrap.min.css" %}">
    <!-- Plugins -->
    <link rel="stylesheet" href="{% static "/assets/css/vendor/bootstrap-slider.min.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/jquery.horizontalmenu.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/jquery-stack-menu.min.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/fancybox.min.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/nice-select.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/vendor/nouislider.min.css" %}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static "/assets/css/main.css" %}">
    <link rel="stylesheet" href="{% static "/assets/css/colors/orange-color.css" %}" id="colorswitch">
</head>

<body>
    <div class="wrapper">
        <!-- Start main-content -->
        {% if form.errors %}
        <div class="errors">
          <ul>
            {% for error in form.errors.values %}
              {% for e in error %}
                <li style="text-align: center; color: red;" >{{ e }}</li>
              {% endfor %}
            {% endfor %}
          </ul>
        </div>
      {% endif %}
        <main class="main-content dt-sl mt-4 mb-3">
            <div class="container main-container">
                <div class="row">
                    <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                        <div class="logo-area text-center mb-3">
                            <a href="#"><img src="{% static "/assets/img/logo.png" %}" class="img-fluid" alt="logo"></a>
                        </div>
                        <div class="auth-wrapper form-ui border pt-4">
                            <div class="section-title title-wide mb-1 no-after-title-wide">
                                <h2 class="font-weight-bold">تغییر رمز عبور</h2>
                            </div>
                            <form action="{% url 'pass_change' %}" method="post" >
                                {% csrf_token %}
                                <div class="form-row-title">
                                    <h3>رمز عبور قبلی</h3>
                                </div>
                                <div class="form-row with-icon">
                                    <input type="password" class="input-ui pr-2"
                                        placeholder="رمز عبور خود را وارد نمایید" name="current_password" id="current_password" required >
                                    <i class="mdi mdi-lock-open-variant-outline"></i>
                                </div>
                                <div class="form-row-title">
                                    <h3>رمز عبور جدید</h3>
                                </div>
                                <div class="form-row with-icon">
                                    <input type="password" class="input-ui pr-2"
                                        placeholder="رمز عبور خود را وارد نمایید" name="new_password" id="new_password" required >
                                    <i class="mdi mdi-lock-reset"></i>
                                </div>
                                <div class="form-row-title">
                                    <h3>تکرار رمز عبور جدید</h3>
                                </div>
                                <div class="form-row with-icon">
                                    <input type="password" class="input-ui pr-2"
                                        placeholder="رمز عبور خود را وارد نمایید"  name="confirm_new_password" id="confirm_new_password" required >
                                    <i class="mdi mdi-lock-reset"></i>
                                </div>
                                <div class="form-row mt-3">
                                    <button class="btn-primary-cm btn-with-icon mx-auto w-100" type="submit" >
                                        <i class="mdi mdi-lock-reset"></i>
                                        تغییر رمز عبور
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- End main-content -->
        <!-- Start mini-footer -->
        <footer class="mini-footer dt-sl">
            <div class="container main-container">
                <div class="row">
                    <div class="col-12">
                        <ul class="mini-footer-menu">
                            <li><a href="{% url 'app_market:blog' %}">درباره مرچ مارکت</a></li>
                        </ul>
                    </div>
                    <div class="col-12 mt-2 mb-3">
                        <div class="footer-light-text">
                            مرچ مارکت
                        </div>
                    </div>
                    <div class="col-12 text-center">
                        <div class="copy-right-mini-footer">
                            merch market
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End mini-footer -->
    </div>
    <!-- colorPanel -->
    <div id="colorswitch-option">
        <button><i class="mdi mdi-settings"></i></button>
        <ul>
            <li class="active" data-path="{% static "/assets/css/colors/orange-color.css" %}"><span
                    style="background-color: #ff9800;"></span></li>
            <li data-path="{% static "/assets/css/colors/amber-color.css" %}"><span style="background-color: #ffab00;"></span></li>
            <li data-path="{% static "/assets/css/colors/blue-color.css" %}"><span style="background-color: #2979ff;"></span></li>
            <li data-path="{% static "/assets/css/colors/blue-grey-color.css" %}"><span style="background-color: #607d8b;"></span>
            </li>
            <li data-path="{% static "/assets/css/colors/brown-color.css" %}"><span style="background-color: #795548;"></span></li>
            <li data-path="{% static "/assets/css/colors/cyan-color.css" %}"><span style="background-color: #00bcd4;"></span></li>
            <li data-path="{% static "/assets/css/colors/green-color.css" %}"><span style="background-color: #4caf50;"></span></li>
            <li data-path="{% static "/assets/css/colors/indigo-color.css" %}"><span style="background-color: #3f51b5;"></span></li>
            <li data-path="{% static "/assets/css/colors/lime-color.css" %}"><span style="background-color: #cddc39;"></span></li>
            <li data-path="{% static "/assets/css/colors/default.css" %}"><span style="background-color: #f7858d;"></span></li>
            <li data-path="{% static "/assets/css/colors/red-color.css" %}"><span style="background-color: #f44336;"></span></li>
            <li data-path="{% static "/assets/css/colors/teal-color.css" %}"><span style="background-color: #009688;"></span></li>
            <li data-path="{% static "/assets/css/colors/purple-color.css" %}"><span style="background-color: #9c27b0;"></span></li>
        </ul>
    </div>
    <!-- end colorPanel -->
    <!-- Core JS Files -->
    <script src="{% static "/assets/js/vendor/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/popper.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/bootstrap.min.js" %}"></script>
    <!-- Plugins -->
    <script src="{% static "/assets/js/vendor/bootstrap-slider.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/owl.carousel.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/owl.carousel2.thumbs.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/jquery.nicescroll.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/nouislider.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/jquery.horizontalmenu.js" %}"></script>
    <script src="{% static "/assets/js/vendor/jquery-stack-menu.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/jquery.fancybox.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/countdown.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/wNumb.js" %}"></script>
    <script src="{% static "/assets/js/vendor/ResizeSensor.min.js" %}"></script>
    <script src="{% static "/assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
    <!-- Main JS File -->
    <script src="{% static "/assets/js/main.js" %}"></script>
</body>

</html>